// Copyright 2017 Google Inc. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

// Command firestore_snippets contains runnable snippet code for Cloud Spanner.
package main

import (
	"fmt"
	"log"
	"os"

	"golang.org/x/net/context"

	"gocloud-exp/firestore"
)

// [START fs_class_definition]

// Coordinates represent the location of a point in the geographic coordinate system.
type Coordinates struct {
	Latitude  float64 `firestore:"latitude,omitempty"`
	Longitude float64 `firestore:"longitude,omitempty"`
}

// City represents a city.
type City struct {
	Name        string      `firestore:"name,omitempty"`
	Weather     string      `firestore:"weather,omitempty"`
	Population  int64       `firestore:"population,omitempty"`
	Country     string      `firestore:"country,omitempty"`
	Capital     bool        `firestore:"capital,omitempty"`
	Coordinates Coordinates `firestore:"coordinates,omitempty"`
}

// [END fs_class_definition]

func main() {
	ctx := context.Background()

	projectID := os.Getenv("GCLOUD_PROJECT")
	if projectID == "" {
		log.Fatalf("Set Firebase project ID via GCLOUD_PROJECT env variable.")
	}

	client, err := firestore.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Cannot create client: %v", err)
	}
	defer client.Close()

	if err := addDocAsMap(ctx, client); err != nil {
		log.Fatalf("Cannot add document as map: %v", err)
	}
	if err := addDocDataTypes(ctx, client); err != nil {
		log.Fatalf("Cannot add document with more data types: %v", err)
	}
	if err := addDocAsEntity(ctx, client); err != nil {
		log.Fatalf("Cannot add document as entity: %v", err)
	}
	if err := addDocAfterAutoGeneratedID(ctx, client); err != nil {
		log.Fatalf("Cannot add document after generating ID: %v", err)
	}
	if err := updateDoc(ctx, client); err != nil {
		log.Fatalf("Cannot update doc: %v", err)
	}
	if err := updateDocMultiple(ctx, client); err != nil {
		log.Fatalf("Cannot update multiple docs: %v", err)
	}
	if err := updateDocNested(ctx, client); err != nil {
		log.Fatalf("Cannot update nested doc: %v", err)
	}
	if err := deleteDoc(ctx, client); err != nil {
		log.Fatalf("Cannot delete doc: %v", err)
	}
	if err := runSimpleTransaction(ctx, client); err != nil {
		log.Fatalf("Cannot run simple job in transaction: %v", err)
	}
	if err := infoTransaction(ctx, client); err != nil {
		log.Fatalf("Cannot return info in transaction: %v", err)
	}

	if err := prepareRetrieve(ctx, client); err != nil {
		log.Fatalf("Cannot prepare for retrieve samples: %v", err)
	}

	doc, err := docAsMap(ctx, client)
	if err != nil {
		log.Fatalf("Cannot get doc as map: %v", err)
	}
	fmt.Printf("Retrieved doc as map: %v\n", doc)

	city, err := docAsEntity(ctx, client)
	if err != nil {
		log.Fatalf("Cannot get doc as entity: %v", err)
	}
	fmt.Printf("Retrieved doc as entity: %v\n", city)

	if err := multipleDocs(ctx, client); err != nil {
		log.Fatalf("Cannot retrieve capital cities: %v", err)
	}
	if err := allDocs(ctx, client); err != nil {
		log.Fatalf("Cannot retrieve all docs: %v", err)
	}
}

// TODO(jbd): Add tests.
